import streamlit as st
import os
import json
import time
from datetime import datetime
from dotenv import load_dotenv
from google import genai
from interview_state import InterviewState
from interview_agent import InterviewAgent
from fpdf import FPDF
from streamlit_mic_recorder import speech_to_text

# --- PAGE CONFIGURATION (Must be first) ---
st.set_page_config(
    page_title="MockMate Pro | AI Career Coach",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CUSTOM CSS: THE "WOW" FACTOR ---
st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Outfit', sans-serif;
    }
    
    .stApp {
        background: radial-gradient(circle at 10% 20%, #0f172a 0%, #1e293b 90%);
        background-attachment: fixed;
    }
    
    div[data-testid="stChatMessage"] {
        background: rgba(255, 255, 255, 0.05);
        backdrop-filter: blur(10px);
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 20px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
        box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
    }

    div[data-testid="stChatMessage"]:has(div[data-testid="chatAvatarIcon-user"]) {
        background: linear-gradient(135deg, rgba(59, 130, 246, 0.2) 0%, rgba(37, 99, 235, 0.2) 100%);
        border-right: 4px solid #60a5fa;
    }
    
    div[data-testid="stChatMessage"]:has(div[data-testid="chatAvatarIcon-assistant"]) {
        background: linear-gradient(135deg, rgba(168, 85, 247, 0.1) 0%, rgba(147, 51, 234, 0.1) 100%);
        border-left: 4px solid #c084fc;
    }
    
    div[data-testid="stChatMessage"] p, div[data-testid="stChatMessage"] div {
        color: #e2e8f0 !important;
        font-size: 1.05rem;
        line-height: 1.6;
    }

    .stButton>button {
        width: 100%;
        border-radius: 12px;
        height: 3.5em;
        background: linear-gradient(90deg, #4f46e5, #7c3aed);
        color: white;
        font-weight: 700;
        border: none;
        letter-spacing: 1px;
        box-shadow: 0 4px 15px rgba(124, 58, 237, 0.4);
        transition: all 0.3s ease;
    }
    .stButton>button:hover {
        transform: scale(1.03);
        box-shadow: 0 8px 25px rgba(124, 58, 237, 0.6);
    }
    
    .stTextInput>div>div>input {
        background-color: rgba(30, 41, 59, 0.8);
        color: white;
        border: 1px solid rgba(255, 255, 255, 0.1);
        border-radius: 12px;
        padding: 10px 15px;
    }
    
    div[data-testid="metric-container"] {
        background: rgba(255, 255, 255, 0.03);
        border: 1px solid rgba(255, 255, 255, 0.05);
        border-radius: 15px;
        padding: 20px;
    }
    div[data-testid="metric-container"] label {
        color: #94a3b8;
    }
    div[data-testid="metric-container"] div {
        color: #f8fafc;
        font-size: 1.8rem !important;
    }
    
    .stProgress > div > div > div > div {
        background-image: linear-gradient(to right, #4f46e5, #ec4899);
    }
    </style>
""", unsafe_allow_html=True)

# --- INIT & SETUP ---
load_dotenv()
API_KEY = os.getenv("GEMINI_API_KEY")
MODEL_NAME = "gemini-2.5-flash-preview-09-2025" 

if not API_KEY:
    st.error("⚠️ API Key Missing. Please check .env file.")
    st.stop()

try:
    client = genai.Client(api_key=API_KEY)
except Exception as e:
    st.error(f"Client Error: {e}")
    st.stop()

# --- STREAMING HELPER ---
def stream_text(text, delay=0.03):
    for word in text.split(" "):
        yield word + " "
        time.sleep(delay)

# --- ADVANCED PDF GENERATION CLASS ---
class PDFReport(FPDF):
    def header(self):
        # Branding Bar
        self.set_fill_color(15, 23, 42) # Dark Navy
        self.rect(0, 0, 210, 30, 'F')
        
        self.set_font('Arial', 'B', 20)
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, 'MockMate Pro', 0, 1, 'L')
        
        self.set_font('Arial', 'I', 10)
        self.set_text_color(148, 163, 184) # Slate 400
        self.cell(0, -15, 'AI-Powered Performance Analysis', 0, 1, 'R')
        self.ln(25)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by MockMate Pro', 0, 0, 'C')

    def section_title(self, label):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(79, 70, 229) # Indigo 600
        self.cell(0, 10, label.upper(), 0, 1, 'L')
        self.set_draw_color(226, 232, 240)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def draw_score_card(self, overall, tech, comm):
        # Draw Container
        self.set_fill_color(248, 250, 252)
        self.set_draw_color(226, 232, 240)
        self.rect(10, self.get_y(), 190, 45, 'DF')
        
        # Overall Score Circle (Simulated)
        start_y = self.get_y() + 5
        self.set_font('Arial', 'B', 30)
        self.set_text_color(124, 58, 237) # Purple
        self.set_xy(15, start_y + 5)
        self.cell(40, 15, f"{overall}/5", 0, 2, 'C')
        
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100, 116, 139)
        self.cell(40, 5, "OVERALL RATING", 0, 0, 'C')

        # Progress Bars Logic
        bar_x = 70
        bar_w = 120
        
        # Technical Bar
        self.set_xy(bar_x, start_y + 5)
        self.set_font('Arial', 'B', 10)
        self.set_text_color(0, 0, 0)
        self.cell(30, 5, "Technical Skills", 0, 0)
        self.set_fill_color(226, 232, 240) # Grey background
        self.rect(bar_x + 35, start_y + 6, bar_w - 35, 3, 'F')
        self.set_fill_color(59, 130, 246) # Blue fill
        fill_width = (tech / 5) * (bar_w - 35)
        self.rect(bar_x + 35, start_y + 6, fill_width, 3, 'F')
        self.set_xy(bar_x + bar_w + 2, start_y + 5)
        self.cell(10, 5, str(tech), 0, 1)

        # Communication Bar
        self.set_xy(bar_x, start_y + 18)
        self.cell(30, 5, "Communication", 0, 0)
        self.set_fill_color(226, 232, 240)
        self.rect(bar_x + 35, start_y + 19, bar_w - 35, 3, 'F')
        self.set_fill_color(236, 72, 153) # Pink fill
        fill_width = (comm / 5) * (bar_w - 35)
        self.rect(bar_x + 35, start_y + 19, fill_width, 3, 'F')
        self.set_xy(bar_x + bar_w + 2, start_y + 18)
        self.cell(10, 5, str(comm), 0, 1)
        
        self.ln(25)

    def body_text(self, text):
        self.set_font('Arial', '', 11)
        self.set_text_color(51, 65, 85) # Slate 700
        self.multi_cell(0, 6, text)
        self.ln(3)

def clean_text(text):
    """Helper to clean unicode characters for FPDF"""
    if not text: return ""
    return text.encode('latin-1', 'replace').decode('latin-1')

def create_pdf_report(json_data):
    pdf = PDFReport()
    pdf.add_page()
    
    # 1. Report Meta Header
    pdf.set_font('Arial', 'B', 16)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 10, f"Role: {clean_text(json_data.get('candidate_role', 'Candidate'))}", 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d')}", 0, 1)
    pdf.ln(5)

    # 2. Visual Scorecard
    overall = float(json_data.get('overall_score', 0))
    tech = float(json_data.get('technical_score', 0))
    comm = float(json_data.get('communication_score', 0))
    pdf.draw_score_card(overall, tech, comm)

    # 3. Executive Summary
    pdf.section_title("Executive Summary")
    pdf.body_text(clean_text(json_data.get('summary', 'No summary available.')))
    pdf.ln(5)

    # 4. Strengths & Weaknesses Table
    pdf.section_title("Key Takeaways")
    
    y_start = pdf.get_y()
    col_width = 90
    
    # Column 1: Strengths
    pdf.set_xy(10, y_start)
    pdf.set_font('Arial', 'B', 11)
    pdf.set_text_color(22, 163, 74) # Green
    pdf.cell(col_width, 8, "Strengths", 0, 2)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(0,0,0)
    for s in json_data.get('strengths', []):
        pdf.multi_cell(col_width, 5, f"- {clean_text(s)}")
    
    # Save height of left column
    left_col_end = pdf.get_y()

    # Column 2: Weaknesses
    pdf.set_xy(10 + col_width + 10, y_start)
    pdf.set_font('Arial', 'B', 11)
    pdf.set_text_color(220, 38, 38) # Red
    pdf.cell(col_width, 8, "Areas for Improvement", 0, 2)
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(0,0,0)
    for w in json_data.get('weaknesses', []):
        pdf.multi_cell(col_width, 5, f"- {clean_text(w)}")
    
    # Reset Y to below the longest column
    pdf.set_y(max(left_col_end, pdf.get_y()) + 10)

    # 5. Detailed Section Analysis
    pdf.section_title("Stage-by-Stage Analysis")
    
    sections = json_data.get('sections', [])
    if not sections:
        sections = json_data.get('feedback_by_stage', [])

    for section in sections:
        # Check for page break
        if pdf.get_y() > 250: pdf.add_page()
        
        name = section.get('name', section.get('stage', 'Unknown Stage'))
        score = section.get('score', 'N/A')
        feedback = section.get('feedback', '')
        
        pdf.set_font('Arial', 'B', 11)
        pdf.set_fill_color(241, 245, 249)
        pdf.cell(0, 8, f" {clean_text(name)} (Score: {score}/5)", 0, 1, 'L', 1)
        pdf.ln(2)
        pdf.body_text(clean_text(feedback))
        pdf.ln(3)

    # 6. Action Plan
    if pdf.get_y() > 240: pdf.add_page()
    if 'next_steps' in json_data:
        pdf.section_title("Recommended Next Steps")
        pdf.body_text(clean_text(json_data['next_steps']))

    return pdf.output(dest='S').encode('latin-1')

# --- STATE MANAGEMENT ---
if "interview_state" not in st.session_state:
    st.session_state.interview_state = InterviewState()

state = st.session_state.interview_state
agent = InterviewAgent(client, MODEL_NAME, state)

# ==========================================
# UI LAYOUT
# ==========================================

# --- SIDEBAR WITH LIVE STATUS ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/4712/4712009.png", width=90)
    st.title("MockMate Pro")
    st.caption("⚡ Powered by Arya")
    st.divider()
    
    if state.is_active:
        st.markdown("### 🔴 Live Status")
        status_placeholder = st.empty()
        status_placeholder.info(f"Stage: {state.current_stage}")
        
        st.markdown("---")
        st.markdown("**Interview Progress**")
        st.progress(state.current_stage_index / len(state.stages))
        
        st.markdown("---")
        st.warning("🛑 End Session")
        if st.button("Finish & Generate Report"):
            status_placeholder.warning("Compiling Feedback...")
            with st.spinner("Analyzing performance metrics..."):
                try:
                    report = agent.generate_feedback_report()
                    state.final_report_content = report
                    state.is_active = False 
                    st.rerun()
                except Exception as e:
                    st.error(f"Generation Error: {e}")
    
    elif state.final_report_content:
        st.success("✨ Analysis Complete")
        if st.button("Start New Interview"):
            state.reset_state()
            st.rerun()
    else:
        st.info("👋 Waiting to Start")
        st.markdown("Configure your role settings to begin the simulation.")

# --- MAIN CONTENT AREA ---

# 1. LANDING / CONFIGURATION PAGE
if not state.is_active and not state.final_report_content:
    
    st.markdown("<h1 style='text-align: center; color: white; font-size: 3.5rem;'>Ace Your Dream Job</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: #94a3b8; font-size: 1.2rem;'>Real-time AI simulation with voice interaction and instant feedback.</p>", unsafe_allow_html=True)
    st.write("")
    st.write("")

    with st.container():
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.markdown("### 🎯 Target Role")
            role_input = st.text_input("Role Title", placeholder="e.g. Senior Product Manager", label_visibility="collapsed")
            
            st.markdown("### 🧠 Focus Areas")
            focus_input = st.text_area("Skills to Test", placeholder="e.g. Strategy, Metrics, Conflict Resolution", label_visibility="collapsed")

        with col2:
            st.markdown("### 📊 Experience Level")
            exp_input = st.selectbox("Level", ["Intern / Entry-Level", "Junior (1-2 Years)", "Mid-Level (3-5 Years)", "Senior Lead", "Executive"], label_visibility="collapsed")
            
            st.write("")
            st.write("")
            if st.button("🚀 Launch Simulation"):
                if role_input:
                    state.start_interview(role_input, exp_input, focus_input)
                    
                    greeting_prompt = f"Start the interview for a {role_input}. Introduce yourself briefly and ask the first question."
                    with st.spinner("Connecting to AI Interviewer..."):
                        resp, _ = agent.generate_next_response(greeting_prompt)
                        state.add_message("assistant", resp)
                    
                    st.toast("Session Live! Good luck.", icon="🟢")
                    time.sleep(1)
                    st.rerun()
                else:
                    st.toast("Please define a role first.", icon="⚠️")

# 2. ACTIVE INTERVIEW PAGE (Real-Time Chat)
elif state.is_active:
    
    col_h1, col_h2 = st.columns([3, 1])
    with col_h1:
        st.subheader(f"💬 Interviewing: {state.role}")
    with col_h2:
        st.caption("🟢 AI is Listening")
    
    chat_container = st.container(height=500)
    with chat_container:
        for msg in state.transcript:
            avatar = "🤖" if msg["speaker"] == "assistant" else "👤"
            with st.chat_message(msg["speaker"], avatar=avatar):
                st.write(msg["text"])

    if state.last_audio_file and os.path.exists(state.last_audio_file):
        st.audio(state.last_audio_file, format="audio/mp3")

    st.write("")
    input_col1, input_col2 = st.columns([1, 5])
    
    with input_col1:
        voice_text = speech_to_text(
            language='en',
            start_prompt="🎤 Speak",
            stop_prompt="🛑 Stop",
            just_once=True,
            key='STT',
            use_container_width=True
        )
    
    with input_col2:
        text_input = st.chat_input(f"Type your answer here...")

    user_input = voice_text if voice_text else text_input

    if user_input:
        state.add_message("user", user_input)
        with chat_container:
             with st.chat_message("user", avatar="👤"):
                st.write(user_input)

        with chat_container:
            with st.chat_message("assistant", avatar="🤖"):
                response_placeholder = st.empty()
                full_response = ""
                
                with st.spinner("Thinking..."):
                    try:
                        ai_resp, terminated = agent.generate_next_response(user_input)
                        
                        for chunk in stream_text(ai_resp):
                            full_response += chunk
                            response_placeholder.markdown(full_response + "▌") 
                        
                        response_placeholder.markdown(full_response)
                        state.add_message("assistant", ai_resp)

                        if terminated:
                            st.toast("Interview Concluded. Generating Report...", icon="🏁")
                            time.sleep(2)
                            with st.spinner("Finalizing Feedback..."):
                                report = agent.generate_feedback_report()
                                state.final_report_content = report
                                state.is_active = False
                                st.rerun()
                        else:
                            st.rerun()
                            
                    except Exception as e:
                        st.error(f"AI Error: {e}")

# 3. REPORT DASHBOARD (The "Result" Page)
else:
    st.balloons()
    
    st.markdown("<h1 style='text-align: center;'>🎉 Interview Complete!</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: #94a3b8;'>Here is your detailed performance breakdown.</p>", unsafe_allow_html=True)
    st.write("")

    try:
        data = json.loads(state.final_report_content)
        
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Overall Score", f"{data.get('overall_score', 'N/A')}/5", delta="Final Rating")
        with col2:
            st.metric("Communication", f"{data.get('communication_score', 'N/A')}/5", delta="Soft Skills")
        with col3:
            st.metric("Technical", f"{data.get('technical_score', 'N/A')}/5", delta="Hard Skills")

        st.divider()

        c1, c2 = st.columns([2, 1])
        
        with c1:
            st.markdown("### 📝 Executive Summary")
            st.info(data.get("summary", "No summary provided."))
            
            st.markdown("### 🔍 Stage-by-Stage Analysis")
            sections = data.get('sections', [])
            if not sections:
                sections = data.get('feedback_by_stage', [])
                
            for section in sections:
                name = section.get('name', section.get('stage', 'Unknown'))
                score = section.get('score', 0)
                with st.expander(f"{name} (Score: {score}/5)"):
                    st.progress(score/5)
                    st.write(section.get('feedback', ''))

        with c2:
            st.markdown("### 🚀 Improvement Plan")
            with st.container():
                st.markdown("**Strengths**")
                for s in data.get("strengths", ["Great job completing the interview!"]):
                    st.success(f"✅ {s}")
                
                st.write("")
                st.markdown("**Focus Areas**")
                for w in data.get("weaknesses", ["Keep practicing!"]):
                    st.warning(f"⚠️ {w}")

            st.markdown("### 📥 Export Results")
            
            try:
                pdf_bytes = create_pdf_report(data)
                btn_label = "📄 Download Professional PDF"
            except Exception as e:
                pdf_bytes = None
                st.error(f"PDF Generation Failed: {e}")
                btn_label = "⚠️ PDF Unavailable"

            if pdf_bytes:
                st.download_button(
                    label=btn_label,
                    data=pdf_bytes,
                    file_name="MockMate_Professional_Report.pdf",
                    mime="application/pdf"
                )
            
            st.download_button(
                label="💾 Download Raw JSON",
                data=state.final_report_content,
                file_name="interview_data.json",
                mime="application/json"
            )
            
            st.write("")
            if st.button("🔄 Start Fresh Session"):
                state.reset_state()
                st.rerun()

    except json.JSONDecodeError:
        st.error("Error parsing the report. Raw output:")
        st.code(state.final_report_content)